name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PROFILE_PAGE_TOKEN }}

          user: palm7710
          template: classic
          base: header, activity, community, repositories, metadata

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: 1

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 2%

          plugin_topics: yes
          plugin_lines: yes
